-- MySQL Script generated by MySQL Workbench
-- Fri Nov 22 15:51:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_plataforma
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_plataforma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_plataforma` DEFAULT CHARACTER SET utf8 ;
USE `bd_plataforma` ;

-- -----------------------------------------------------
-- Table `bd_plataforma`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_plataforma`.`professor` (
  `idprofessor` INT NOT NULL AUTO_INCREMENT,
  `us_nome` VARCHAR(200) NOT NULL,
  `us_email` VARCHAR(200) NOT NULL,
  `us_senha` VARCHAR(20) NOT NULL,
  `us_nivel_acesso` INT NOT NULL,
  PRIMARY KEY (`idprofessor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_plataforma`.`disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_plataforma`.`disciplinas` (
  `iddisciplina` INT NOT NULL AUTO_INCREMENT,
  `dis_nome` VARCHAR(45) NOT NULL,
  `dis_sigla` VARCHAR(5) NOT NULL,
  `idprofessor` INT NOT NULL,
  PRIMARY KEY (`iddisciplina`),
  INDEX `fk_disciplinas_professor1_idx` (`idprofessor` ASC),
  CONSTRAINT `fk_disciplinas_professor1`
    FOREIGN KEY (`idprofessor`)
    REFERENCES `bd_plataforma`.`professor` (`idprofessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_plataforma`.`questoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_plataforma`.`questoes` (
  `idquestao` INT NOT NULL AUTO_INCREMENT,
  `iddisciplina` INT NOT NULL,
  `ques_triNivel` INT NOT NULL,
  `ques_textoQuestao` TEXT NOT NULL,
  `ques_enunciado` TEXT NOT NULL,
  `ques_alternativaA` TEXT NOT NULL,
  `ques_alternativaB` TEXT NOT NULL,
  `ques_alternativaC` TEXT NOT NULL,
  `ques_alternativaD` TEXT NOT NULL,
  `ques_alternativaE` TEXT NOT NULL,
  `ques_alternativaCorreta` CHAR(1) NOT NULL,
  PRIMARY KEY (`idquestao`),
  INDEX `fk_questoes_disciplinas1_idx` (`iddisciplina` ASC),
  CONSTRAINT `fk_questoes_disciplinas1`
    FOREIGN KEY (`iddisciplina`)
    REFERENCES `bd_plataforma`.`disciplinas` (`iddisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_plataforma`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_plataforma`.`turma` (
  `idturma` INT NOT NULL AUTO_INCREMENT,
  `tur_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idturma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_plataforma`.`simulados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_plataforma`.`simulados` (
  `idsimulado` INT NOT NULL AUTO_INCREMENT,
  `idprofessor` INT NOT NULL,
  `idturma` INT NOT NULL,
  `simu_descricao` VARCHAR(200) NOT NULL,
  `simu_dataCriacao` DATETIME NOT NULL,
  `simu_ativo` INT NOT NULL,
  `simu_conclusao` TINYINT NOT NULL,
  PRIMARY KEY (`idsimulado`),
  INDEX `fk_gerarSimulados_usuarios1_idx` (`idprofessor` ASC),
  INDEX `fk_gerarSimulados_turma1_idx` (`idturma` ASC),
  CONSTRAINT `fk_gerarSimulados_usuarios1`
    FOREIGN KEY (`idprofessor`)
    REFERENCES `bd_plataforma`.`professor` (`idprofessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gerarSimulados_turma1`
    FOREIGN KEY (`idturma`)
    REFERENCES `bd_plataforma`.`turma` (`idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_plataforma`.`questoes_selecionadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_plataforma`.`questoes_selecionadas` (
  `idsimulado` INT NOT NULL,
  `idquestao` INT NOT NULL,
  PRIMARY KEY (`idsimulado`, `idquestao`),
  INDEX `fk_gerarSimulados_has_questoes_questoes1_idx` (`idquestao` ASC),
  INDEX `fk_gerarSimulados_has_questoes_gerarSimulados1_idx` (`idsimulado` ASC),
  CONSTRAINT `fk_gerarSimulados_has_questoes_gerarSimulados1`
    FOREIGN KEY (`idsimulado`)
    REFERENCES `bd_plataforma`.`simulados` (`idsimulado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gerarSimulados_has_questoes_questoes1`
    FOREIGN KEY (`idquestao`)
    REFERENCES `bd_plataforma`.`questoes` (`idquestao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_plataforma`.`simulados_aplicados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_plataforma`.`simulados_aplicados` (
  `idsimulado` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `idturma` INT NOT NULL,
  `iddisciplina` INT NOT NULL,
  `simu_nome` VARCHAR(200) NOT NULL,
  `simu_dataCriacao` DATETIME NOT NULL,
  `simu_ativo` INT NOT NULL,
  `simu_totalQuestoes` INT NOT NULL,
  `simu_descricao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idsimulado`),
  INDEX `fk_gerarSimulados_usuarios1_idx` (`idusuario` ASC),
  INDEX `fk_gerarSimulados_turma1_idx` (`idturma` ASC),
  INDEX `fk_gerarSimulados_disciplinas1_idx` (`iddisciplina` ASC),
  CONSTRAINT `fk_gerarSimulados_usuarios10`
    FOREIGN KEY (`idusuario`)
    REFERENCES `bd_plataforma`.`professor` (`idprofessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gerarSimulados_turma10`
    FOREIGN KEY (`idturma`)
    REFERENCES `bd_plataforma`.`turma` (`idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gerarSimulados_disciplinas10`
    FOREIGN KEY (`iddisciplina`)
    REFERENCES `bd_plataforma`.`disciplinas` (`iddisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_plataforma`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_plataforma`.`alunos` (
  `idalunos` INT NOT NULL AUTO_INCREMENT,
  `idturma` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `matricula` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `pontuacao` INT NULL,
  PRIMARY KEY (`idalunos`),
  INDEX `fk_alunos_turma1_idx` (`idturma` ASC),
  CONSTRAINT `fk_alunos_turma1`
    FOREIGN KEY (`idturma`)
    REFERENCES `bd_plataforma`.`turma` (`idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_plataforma`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_plataforma`.`matricula` (
  `idmatricula` INT NOT NULL AUTO_INCREMENT,
  `idalunos` INT NOT NULL,
  `idsimulado` INT NOT NULL,
  `data` DATETIME NULL,
  INDEX `fk_x_alunos1_idx` (`idalunos` ASC),
  INDEX `fk_x_simulados1_idx` (`idsimulado` ASC),
  PRIMARY KEY (`idmatricula`),
  CONSTRAINT `fk_x_alunos1`
    FOREIGN KEY (`idalunos`)
    REFERENCES `bd_plataforma`.`alunos` (`idalunos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_x_simulados1`
    FOREIGN KEY (`idsimulado`)
    REFERENCES `bd_plataforma`.`simulados` (`idsimulado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_plataforma`.`simulado_resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_plataforma`.`simulado_resposta` (
  `idmatricula` INT NOT NULL,
  `idsimulado` INT NOT NULL,
  `idquestao` INT NOT NULL,
  `resposta` CHAR(1) NULL,
  PRIMARY KEY (`idmatricula`, `idsimulado`, `idquestao`),
  INDEX `fk_questoes_selecionadas_has_matricula_matricula1_idx` (`idmatricula` ASC),
  INDEX `fk_questoes_selecionadas_has_matricula_questoes_selecionada_idx` (`idsimulado` ASC, `idquestao` ASC),
  CONSTRAINT `fk_questoes_selecionadas_has_matricula_questoes_selecionadas1`
    FOREIGN KEY (`idsimulado` , `idquestao`)
    REFERENCES `bd_plataforma`.`questoes_selecionadas` (`idsimulado` , `idquestao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questoes_selecionadas_has_matricula_matricula1`
    FOREIGN KEY (`idmatricula`)
    REFERENCES `bd_plataforma`.`matricula` (`idmatricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
