@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Nywibml2ZWxfYWNlc3NvIjoxLCJpYXQiOjE3MzMzMTIyNzAsImV4cCI6MTczMzM5ODY3MH0.EgW_NgCR8Yg0ybwlxn1sw_c7Pq1QozGrRsw4gPvi0M8

###########################################
POST http://10.132.224.60:3901/api/login
Content-Type: application/json

{
    "email": "rodrigo.casa@portalsesisp.org.br",
    "senha": "Sesisp@1234"
}

###########################################
POST http://10.132.224.60:3901/api/login
Content-Type: application/json

{
    "email": "alana.freitas@portalsesisp.org.br",
    "senha": "Sesisp@2151"
}

###########################################
POST http://10.132.224.60:3901/api/login/verificarToken
Content-Type: application/json
authorization: {{token}}

###########################################
POST http://10.132.224.60:3901/api/login/listar
Content-Type: application/json
authorization: {{token}}

###########################################
POST http://10.132.224.60:3901/api/login/cadastrarUser
Content-Type: application/json

{
    "nome": "João Silva",
    "email": "joao.silva@escola.com",
    "senha": "123456",
    "nivel_acesso": 2,
    "disciplinasAula": [1, 2, 3]
}



###########################################
GET http://10.132.224.60:3901/api/login/dadosUser
authorization: {{token}}


###########################################
GET http://10.132.224.60:3901/api/simulados/agendados

############################################
POST http://10.132.224.60:3901/api/adm/simulados/criarNovoSimulado
Content-Type: application/json
authorization: {{token}}

{
    "turma_id": 1,
    "descricao": "Simulado de Matemática Básica",
    "professor": 1,
    "status": 1,
    "disciplina_id": 3,
    "questoes": [
        {
            "nivel": "1",
            "texto": "Qual é o resultado de 5 + 3?",
            "enunciado": "Calcule a soma dos números apresentados.",
            "alternativaA": "6",
            "alternativaB": "7",
            "alternativaC": "8",
            "alternativaD": "9",
            "alternativaE": "10",
            "alternativaCorreta": "C"
        }]
}

############################################
DELETE http://10.132.224.60:3901/api/simulados/15
authorization: {{token}}


############################################
GET http://10.132.224.60:3901/api/questoes/questoesDisciplina/2
authorization: {{token}}

#############################################
GET http://10.132.224.60:3901/api/relatorios/rankingGeral
authorization: {{token}}

##############################################
GET http://10.132.224.60:3901/api/relatorios/2
authorization: {{token}}

##############################################
GET http://10.132.224.60:3901/api/relatorios/pontuacao/4
authorization: {{token}}

##############################################
GET http://10.132.224.60:3901/api/adm/simulados/simuladosCriados
authorization: {{token}}

##############################################
PUT http://10.132.224.60:3901/api/adm/simulados/atualizarQuestao
Content-Type: application/json
authorization: {{token}}

{
  "id": 1,
  "disciplina_id": 3,
  "nivel": 1,
  "texto": "Leia atentamente as informações abaixo",
  "enunciado": "Qual das alternativas a seguir é a capital do Brasil?",
  "alternativaA": "Moscou",
  "alternativaB": "Buenos Aires",
  "alternativaC": "Santiago",
  "alternativaD": "Brasília",
  "alternativaE": "Bogotá",
  "alternativaCorreta": "D"
}


