@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Nywibml2ZWxfYWNlc3NvIjoxLCJpYXQiOjE3MzM0OTAwOTQsImV4cCI6MTczMzU3NjQ5NH0.OEgWoJ8rqRkC9z18okZdHlRnbW1LGmXkFqag6FM_y9E
@url=http://10.132.224.60:3901


###########################################
POST {{url}}/api/login
Content-Type: application/json

{
    "email": "rodrigo.casa@portalsesisp.org.br",
    "senha": "Sesisp@1234"
}


###########################################
POST {{url}}/api/login/verificarToken
Content-Type: application/json
authorization: {{token}}

###########################################
POST {{url}}/api/login/listar
Content-Type: application/json
authorization: {{token}}

###########################################
POST {{url}}/api/login/cadastrarUser
Content-Type: application/json

{
    "nome": "João Silva",
    "email": "joao.silva@portalsesisp.org.br",
    "senha": "123456",
    "nivel_acesso": 2,
    "disciplinasAula": [1, 2, 3]
}

###########################################
GET {{url}}/api/login/dadosUser
authorization: {{token}}


###########################################
GET {{url}}/api/alunos/simulados/agendados

############################################
GET {{url}}/api/alunos/simulados/2/questoes


###########################################
GET {{url}}/api/adm/turmas
authorization: {{token}}

###########################################
GET {{url}}/api/adm/disciplinas/buscarPorProfessor
authorization: {{token}}

############################################
POST {{url}}/api/adm/simulados/criarNovoSimulado
Content-Type: application/json
authorization: {{token}}

{
    "turma_id": 1,
    "descricao": "Simulado de Matemática Básica",
    "professor": 1,
    "status": 1,
    "disciplina_id": 3,
    "questoes": [
        {
            "nivel": "1",
            "texto": "Qual é o resultado de 5 + 3?",
            "enunciado": "Calcule a soma dos números apresentados.",
            "alternativaA": "6",
            "alternativaB": "7",
            "alternativaC": "8",
            "alternativaD": "9",
            "alternativaE": "10",
            "alternativaCorreta": "C"
        }]
}

############################################
DELETE {{url}}/api/adm/simulados/68
authorization: {{token}}


############################################
GET {{url}}/api/adm/simulados/68
authorization: {{token}}

############################################
GET {{url}}/api/adm/questoes/questoesDisciplina/3
authorization: {{token}}

#############################################
GET {{url}}/api/relatorios/rankingGeral
authorization: {{token}}

##############################################
GET {{url}}/api/alunos/relatorios/31
authorization: {{token}}

##############################################
GET {{url}}/api/relatorios/pontuacao/4
authorization: {{token}}

##############################################
GET {{url}}/api/adm/simulados/simuladosCriados
authorization: {{token}}

##############################################



