###########################################
POST http://10.132.224.58:3313/api/login

###
POST http://localhost:3313/api/login
Content-Type: application/json

{
    "email": "alana.freitas@portalsesisp.org.br",
    "senha": "Sesisp@2151"
}

###########################################
POST http://10.132.224.58:3313/api/login/cadastrarUser
Content-Type: application/json

{
    "nome": "Luciana Leiva Gimenes de Carvalho",
    "email": "luciana.gimenes@portalsesisp.org.br",
    "senha": "Sesisp@4545",
    "nivel_acesso": 1
}

###########################################
GET http://10.132.224.58:3313/api/login/4

###########################################
GET http://10.132.224.58:3313/api/simulados/agendados


